### ISSUE TITLE
The value in the database is not cleared

### ISSUE THREAD

**Issue by ivan-s-1** [mnoskov/clientsettings#14]
Привет.
Если ввести например в переменную "[(client_ur_adres)]" данные, сохранить, а потом удалить, чтоб поле было пустое, данные продолжают храниться в базе mysql.
Скрины приложил.
Как решить эту проблему ? так как данные из некоторых переменных использую в своих сниппетах и при использовании условия IF не получается например проверить на пустоту значение.

![2019-05-31_13-51-39](https://user-images.githubusercontent.com/24613445/58693935-529a4900-83ab-11e9-97e8-5bcffe869270.jpg)
![2019-05-31_13-51-25](https://user-images.githubusercontent.com/24613445/58693937-529a4900-83ab-11e9-98d5-d08e5ad72eab.jpg)

**Comment by mnoskov** [comment]
Покажите конфиг

**Comment by ivan-smirnyagin-1** [comment]
[example.txt](https://github.com/mnoskov/clientsettings/files/3240707/example.txt)

**Comment by mnoskov** [comment]
На последней версии такую ошибку не встречаю. Похоже что вот этот фикс - https://github.com/mnoskov/clientsettings/commit/07be0b92b15c5d25bd841c5ff11eea5953dad0b2

**Comment by ivan-smirnyagin-1** [comment]
понял, спасибо

**Comment by ivan-smirnyagin-1** [comment]
версия evolution Evolution 1.4.9
