### ISSUE TITLE
Ошибка в Evolution 1.4.10

### ISSUE THREAD

**Issue by mmmborman** [mnoskov/clientsettings#15]
Добрый день. Evolution 1.4.10

Подскажите как можно исправить переключение вкладок в режиме «Использовать глобальные вкладки». В этом режиме они не работают

http://modx.im/uploads/images/00/17/31/2019/11/26/821473.jpg

http://modx.im/uploads/images/00/17/31/2019/11/26/6e2948.jpg

При установке плагина, пропадает вкладка SEO и все поля переходят в Общую вкладку.

http://modx.im/uploads/images/00/17/31/2019/11/26/8d0ab8.jpg

**Comment by mnoskov** [comment]
Да, видимо глобальные вкладки смотрят только на идентификатор модуля. Не знаю, что вам предложить.
По поводу вкладки SEO, у меня такой проблемы нет. Что это за вкладка, как создается?

**Comment by mmmborman** [comment]
> По поводу вкладки SEO, у меня такой проблемы нет. Что это за вкладка, как создается?

Это которая по умолчанию в каждом ресурсе. Их три по умолчанию: Общие, Настройки страницы, SEO http://my.jetscreenshot.com/11823/20191126-8rii-29kb.jpg

и все поля title, desc и т.д съезжают в Общие в конец

**Comment by mnoskov** [comment]
Не вижу связи, они же даже в разных фреймах. Проверьте чанк mm_rules, активность плагина ManagerManager. 

Вот у меня они вместе работают:
![2019-11-27_15-08-40](https://user-images.githubusercontent.com/8789957/69714269-f466dc80-1127-11ea-823b-a31c2785f8a6.png)

**Comment by mmmborman** [comment]
Переустановил плагин, заработало. Извините за беспокойство.
