### ISSUE TITLE
Добавление настроек в редакторе - нажатие + очищает строку

### ISSUE THREAD

**Issue by sashabeep** [mnoskov/clientsettings#17]
![Feb-06-2020 14-05-56](https://user-images.githubusercontent.com/5689796/73931829-0adca180-48ea-11ea-8a62-b85d3e515b87.gif)

Если заполнить поля и нажать + добавляется новая пустая строка и текущая строка очищается

**Comment by mnoskov** [comment]
https://github.com/mnoskov/clientsettings/commit/26e850a538798acb3a39481621344010547fa6c7
