### ISSUE TITLE
Extra submenu items limited to one?

### ISSUE THREAD

**Issue by fourroses666** [mnoskov/clientsettings#18]
Seems I can only add only one extra (sub)menu item. Is it a bug or is it supposed to be like that?

![cs](https://user-images.githubusercontent.com/523389/78893813-415ea600-7a6c-11ea-904f-c4f1130640c7.jpg)

    'menu' => [
        'alias' => 'submenu',
        'caption' => 'Theme',
        'icon' => 'fa-something',
    ],

**Comment by mnoskov** [comment]
Submenu items are grouped by alias

**Comment by fourroses666** [comment]
Thanks, now I know :)
