### ISSUE TITLE
default_text doesn't work

### ISSUE THREAD

**Issue by fourroses666** [mnoskov/clientsettings#19]
Doesn't seem to work on my site: 'default_text' is empty.

        'field_text' => [
            'caption' => 'Текст',
            'type'  => 'text',
            'note'  => 'Это просто текст',
            'default_text' => 'Значение по умолчанию',
        ],

**Comment by mnoskov** [comment]
On my it works.

**Comment by fourroses666** [comment]
Don't know whats wrong with my site.
I just tested it again without result:

default_text --> means it fills the input field?

![defaulttext](https://user-images.githubusercontent.com/523389/79635415-144b7b00-8171-11ea-82af-780e09d5e4b0.jpg)

EVO 2.0.2 
CS recently installed from Extras

Its not a big issue but just doesn't seem to work with me.

**Comment by mnoskov** [comment]
No, it cannot fill value befoe you saved it

**Comment by fourroses666** [comment]
After saving I get the same result unfortunately.
But again, its not a big deal. [[IF?]] can be used for front-end.
