### ISSUE TITLE
Image select (imageradio)

### ISSUE THREAD

**Issue by fourroses666** [mnoskov/clientsettings#20]
Would be great to have an image/thumb select option.
The client can choose a theme by clicking on a preview thumb.

Just some crazy example:
```
    'field_imageradio' => [
        'caption' => 'Theme select',
        'type'  => 'imageradio',
        'elements' => 'Dark theme 1==1||Light theme 2==2',
        'elements-images' => '/images/dark-theme.jpg==1||/images/light-theme.jpg==2',
    ],
```

Something like this:
![theme-selection-list](https://user-images.githubusercontent.com/523389/79508533-0515e180-803a-11ea-8354-8bf0ab2ecee9.jpg)

Don't know if you would find this useful.
I could do it with CSS as bypass but rather have an option to add an image/thumb before the radiobox.

`#tab_tab20 .checkbox:nth-child(1){background-image:url(); ...} ...`

**Comment by mnoskov** [comment]
You can use next example:
```php
'row_template' => [
    'caption' => 'Шаблон вывода категорий',
        'type' => 'imageradio',
        'layout' => 'horizontal',
        'elements' => [
            'categories_tpl1' => '/assets/plugins/pagebuilder/images/categories_tpl1.png',
            'categories_tpl2' => '/assets/plugins/pagebuilder/images/categories_tpl2.png',
            'categories_tpl3' => '/assets/plugins/pagebuilder/images/categories_tpl3.png',
        ],
        'default' => 'categories_tpl1',
    ],
],
```

**Comment by mnoskov** [comment]
Sorry, wrong plugin :) Thought it's Pagebuilder

**Comment by mnoskov** [comment]
I think this can be solved by customtv

**Comment by fourroses666** [comment]
Hmm, I don't see how this can be done with MultiTV. 
I don't want to add multiple items, just want to be able to select a theme _(which is an image radiobutton)._

**Comment by fourroses666** [comment]
Oh sorry, I misunderstood. Will try.

https://github.com/mnoskov/clientsettings/blob/master/assets/modules/clientsettings/config/tab20.php.sample
